../X-CUBE-AI/App/app_x-cube-ai.c:118:13:ai_log_err	2
../X-CUBE-AI/App/app_x-cube-ai.c:131:12:ai_boostrap	4
../X-CUBE-AI/App/app_x-cube-ai.c:174:12:ai_run	2
../X-CUBE-AI/App/app_x-cube-ai.c:189:5:acquire_and_process_data	6
../X-CUBE-AI/App/app_x-cube-ai.c:226:5:post_process	5
../X-CUBE-AI/App/app_x-cube-ai.c:263:6:synchronize_UART	3
../X-CUBE-AI/App/app_x-cube-ai.c:298:6:MX_X_CUBE_AI_Init	1
../X-CUBE-AI/App/app_x-cube-ai.c:307:6:MX_X_CUBE_AI_Process	6
../X-CUBE-AI/App/app_x-cube-ai.c:378:9:ai_mnetwork_is_valid	4
../X-CUBE-AI/App/app_x-cube-ai.c:388:26:ai_mnetwork_handle	6
../X-CUBE-AI/App/app_x-cube-ai.c:400:6:ai_mnetwork_release_handle	4
../X-CUBE-AI/App/app_x-cube-ai.c:411:13:ai_mnetwork_find	4
../X-CUBE-AI/App/app_x-cube-ai.c:428:10:ai_mnetwork_create	8
../X-CUBE-AI/App/app_x-cube-ai.c:470:11:ai_mnetwork_destroy	3
../X-CUBE-AI/App/app_x-cube-ai.c:485:9:ai_mnetwork_get_report	2
../X-CUBE-AI/App/app_x-cube-ai.c:496:10:ai_mnetwork_get_error	2
../X-CUBE-AI/App/app_x-cube-ai.c:511:9:ai_mnetwork_init	3
../X-CUBE-AI/App/app_x-cube-ai.c:528:8:ai_mnetwork_run	2
../X-CUBE-AI/App/app_x-cube-ai.c:540:8:ai_mnetwork_forward	2
../X-CUBE-AI/App/app_x-cube-ai.c:551:6:ai_mnetwork_get_private_handle	4
